"""empty message

Revision ID: 01d49db1d17c
Revises: 7a8030ecc8e1
Create Date: 2021-05-22 05:38:41.400826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d49db1d17c'
down_revision = '7a8030ecc8e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('company', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('user_type', sa.String(length=120), nullable=False))
    op.add_column('wish_list', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish_list', 'quantity')
    op.drop_column('user', 'user_type')
    op.drop_column('product', 'company')
    # ### end Alembic commands ###
