"""empty message

Revision ID: 14c135e70420
Revises: 32f8f76cbe49
Create Date: 2021-05-16 02:45:40.343050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c135e70420'
down_revision = '32f8f76cbe49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('enlace', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'product', ['enlace'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('product', 'enlace')
    # ### end Alembic commands ###
