"""empty message

Revision ID: 407042d83ac0
Revises: 76b490ae9418
Create Date: 2021-05-16 19:38:12.433399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407042d83ac0'
down_revision = '76b490ae9418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('url', sa.String(length=1024), nullable=False))
    op.drop_column('product', 'enlace')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('enlace', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('product', 'url')
    # ### end Alembic commands ###
