"""empty message

Revision ID: 48cb6002aa3a
Revises: 553f7a0a2539
Create Date: 2021-05-17 00:30:37.161149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48cb6002aa3a'
down_revision = '553f7a0a2539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('cardid', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'cardid')
    # ### end Alembic commands ###
