"""empty message

Revision ID: 76b490ae9418
Revises: 14c135e70420
Create Date: 2021-05-16 06:09:04.197931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b490ae9418'
down_revision = '14c135e70420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_categoria_key', 'product', type_='unique')
    op.drop_constraint('product_enlace_key', 'product', type_='unique')
    op.drop_constraint('product_item_key', 'product', type_='unique')
    op.drop_constraint('product_marca_key', 'product', type_='unique')
    op.drop_constraint('product_nombre_key', 'product', type_='unique')
    op.drop_constraint('product_precio_key', 'product', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('product_precio_key', 'product', ['precio'])
    op.create_unique_constraint('product_nombre_key', 'product', ['nombre'])
    op.create_unique_constraint('product_marca_key', 'product', ['marca'])
    op.create_unique_constraint('product_item_key', 'product', ['item'])
    op.create_unique_constraint('product_enlace_key', 'product', ['enlace'])
    op.create_unique_constraint('product_categoria_key', 'product', ['categoria'])
    # ### end Alembic commands ###
