"""empty message

Revision ID: 994f5362c009
Revises: 407042d83ac0
Create Date: 2021-05-16 20:31:58.858184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994f5362c009'
down_revision = '407042d83ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('enlace', sa.String(length=1024), nullable=False))
    op.drop_column('product', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('url', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.drop_column('product', 'enlace')
    # ### end Alembic commands ###
