"""empty message

Revision ID: b2bc2c81546b
Revises: dfd35080b644
Create Date: 2021-05-16 02:55:18.448961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2bc2c81546b'
down_revision = 'dfd35080b644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_last_name_key', 'user', type_='unique')
    op.drop_constraint('user_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.create_unique_constraint('user_last_name_key', 'user', ['last_name'])
    # ### end Alembic commands ###
